version: '3.7'
services:
  service-1:
    image: georgerhodes/service-1:latest
    build: ./service-1 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
    depends_on: 
      - database
    environment: 
      - MYSQL_ROOT_PASSWORD=cheeky
  service-2:
    image: georgerhodes/service-2:latest      
    build: ./service-2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 3
  service-3:
    image: georgerhodes/service-3:latest
    build: ./service-3
    ports:
    - target: 5002
      protocol: tcp
    deploy:
      replicas: 3
  service-4:
    image: georgerhodes/service-4:latest      
    build: ./service-4
    ports:
    - target: 5003
      protocol: tcp
    deploy:
      replicas: 3
  database:
    image: georgerhodes/database:latest
    build: ./database
    ports:
    - target: 3306
    volumes:
    - type: volume
      source: ticket_data
      target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cheeky 
volumes:
  ticket_data: